PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#/>
PREFIX  dbo:    <http://dbpedia.org/ontology/>
PREFIX  gn:     <http://www.geonames.org/ontology#>
PREFIX  dc:     <http://purl.org/dc/elements/1.1/>
PREFIX  igeo:   <http://rdf.insee.fr/def/geo>

# Value
CONSTRUCT {
    ?URI a dbo:Statistic ;
    igeo:codeRegion ?URI_REGION ;
    gn:name ?Region ;
    dbo:sex ?Sexe ;
    dbo:creator ?code_type_uai ;
    dbo:alias ?type_administration ;
    dbo:year ?Annee ;
    dbo:roleInEvent ?type_personnel ;
    dc:type ?Indicateur ;
    dbo:status ?etat_donnees.

    ?URI_REGION owl:sameAs ?URI_REGION_DBPEDIA;
                owl:sameAs ?URI_REGION_CONCOURS;


}
FROM <file:dataset_rd.csv>
WHERE {
    BIND (URI(?Valeur) as ?URI)
    BIND (URI(CONCAT('http://research-funding.org/administration/region/', ?code_region) as ?URI_REGION)
    BIND (URI(CONCAT('http://fr.dbpedia.org/page/', ?code_region)) AS ?URI_REGION_DBPEDIA)
    BIND (URI(CONCAT('http://id.insee.fr/geo/region/'), ?code_region) AS ?URI_REGION_INSEE)
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?code_region)) as ?URI_REGION_CONCOURS)

}
