PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://example.org/>
PREFIX dbo:  <http://dbpedia.org/ontology/>
PREFIX dc:  <http://purl.org/dc/elements/1.1/>
PREFIX  gn: <http://www.geonames.org/ontology#>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX  igeo:   <http://rdf.insee.fr/def/geo>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

select ?y ?region
where {
	?x igeo:codeRegion ?region.
	?region owl:sameAs ?region_dataset.
	GRAPH <http://concours-etoiles-europe.org/ns#> {
		?y dbp:region ?region_dataset
	}
}
group by ?y ?region